const TOPICS = {
  LOAD: "TOPICS_LOAD",
  LOAD_SUCCESS: "TOPICS_LOAD_SUCCESS",
  LOAD_FAIL: "TOPICS_LOAD_FAIL",
  ADD_COMMENT: "ADD_COMMENT",
  ADD_THREAD: "ADD_THREAD",
};

export { TOPICS };
